//go:build portable

package main

import _ "embed"

// payload.zip is a zip of electron-builder's win-unpacked output, generated by
// scripts/build-portable.mjs immediately before this build and deleted after.
// Only the `portable` build tag pulls it in, so the plain stub stays ~2MB.

//go:embed payload.zip
var payload []byte

const hasPayload = true

func payloadBytes() []byte { return payload }
