// Regenerates the encoding fixtures in tests/corpus, plus the large-file
// fixture used for manual testing.
//
// These files cannot be authored in an editor and committed as-is: git and
// most editors would normalise them back to UTF-8, which is exactly the case
// they exist to test. .gitattributes marks tests/corpus as binary so the bytes
// survive a round-trip through the repo.
//
//   node scripts/gen-corpus.mjs

import { writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import iconv from 'iconv-lite'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const corpus = join(root, 'tests', 'corpus')

function report(name, buf) {
  const head = [...buf.subarray(0, 8)].map((b) => b.toString(16).padStart(2, '0')).join(' ')
  process.stdout.write(`  ${name.padEnd(16)} ${String(buf.length).padStart(9)} bytes   ${head}\n`)
}

// --- CP1252 -----------------------------------------------------------------
// Every high character here is a byte that is illegal as standalone UTF-8, so
// a reader that ignores sniffing and assumes UTF-8 produces U+FFFD and the
// test fails loudly rather than subtly.
const cp1252Text = [
  '# CP1252 Test',
  '',
  'Smart quotes: “double” and ‘single’',
  'Dashes: en – dash, em — dash',
  'Ellipsis… and a bullet •',
  'Currency: € 100, £ 50, ¥ 200',
  'Accents: café, naïve, résumé, über, señor',
  'Symbols: © ® ™ ° ½ ¼',
  'Maths: 5 × 3 ÷ 2 ± 1',
  '',
].join('\r\n')

const cp1252 = iconv.encode(cp1252Text, 'win1252')
writeFileSync(join(corpus, 'cp1252.md'), cp1252)
report('cp1252.md', cp1252)

// --- UTF-16 -----------------------------------------------------------------
const utf16Text = [
  '# UTF-16 Test',
  '',
  'ASCII text, then non-BMP so surrogate pairs are exercised.',
  '',
  'Greek: αβγδε',
  'CJK: 你好世界',
  'Emoji (surrogate pairs): \u{1F600} \u{1F680} \u{1F4DD}',
  'Accents: café naïve',
  '',
].join('\r\n')

const utf16leBody = Buffer.from(utf16Text, 'utf16le')
const utf16le = Buffer.concat([Buffer.from([0xFF, 0xFE]), utf16leBody])
writeFileSync(join(corpus, 'utf16le.md'), utf16le)
report('utf16le.md', utf16le)

// Byte-swap the LE body rather than re-encoding, so both fixtures are provably
// the same text.
const beBody = Buffer.from(utf16leBody)
for (let i = 0; i + 1 < beBody.length; i += 2) {
  const t = beBody[i]
  beBody[i] = beBody[i + 1]
  beBody[i + 1] = t
}
const utf16be = Buffer.concat([Buffer.from([0xFE, 0xFF]), beBody])
writeFileSync(join(corpus, 'utf16be.md'), utf16be)
report('utf16be.md', utf16be)

// --- Large file -------------------------------------------------------------
// Not committed (see .gitignore): 2MB of generated filler has no business in
// the repo when it can be reproduced exactly on demand.
const chunks = []
let n = 0
chunks.push('# 2MB Test Document\n\nGenerated by scripts/gen-corpus.mjs.\n\n')

while (chunks.join('').length < 2 * 1024 * 1024) {
  n++
  chunks.push(
    `## Section ${n}\n\n` +
      `Paragraph with **bold**, *italic*, \`code\` and a [link](https://example.com/${n}).\n\n` +
      '```js\n' +
      `function section${n}(value) {\n  return value * ${n}\n}\n` +
      '```\n\n' +
      `| Column A | Column B |\n|---|---|\n| ${n} | ${n * 2} |\n\n` +
      `> Blockquote for section ${n}.\n\n` +
      `- item one\n- item two\n- item three\n\n`,
  )
}

const large = Buffer.from(chunks.join(''), 'utf8')
writeFileSync(join(corpus, '2mb.md'), large)
report('2mb.md', large)

process.stdout.write(`\nWrote fixtures to ${corpus}\n`)
